### ISSUE TITLE
Intellij under osx failed to pass pid lock (lock.getpcmd)

### ISSUE THREAD

**Issue by tomerf8** [spotify/luigi#1654]
It seems that Intellij (and probably other IDE's) will not appear under 'ps -o pid,args', because under osx (Yosemite) they are operating under a different user of some sort (although not root user, I verified that ;) )

* workaround: use 'ps -A -o pid,args' to scan all running processes.

**Comment by javrasya** [comment]
I think this is fixed in [Uses more thorough pid check for locking](https://github.com/spotify/luigi/commit/8c4708d4f2d3c40802d9f9873586aef46cba383f) commit which is in version [2.2.0](https://github.com/spotify/luigi/releases/tag/2.2.0) release

**Comment by Tarrasch** [comment]
Given the low activity of this issue, let's assume that indeed fixed this.

**Comment by Tarrasch** [comment]
@mambistats please stop complaining and send a PR fixing any shortcomings. This is not a paid product with support. Luigi is a community developed product, and that's where you come in.

**Comment by mambistats** [comment]
I just complained because the issue was closed without a fix saying that nobody was complaining. I just wanted to say it is not fixed as assumed because nobody did say anything. I just hoped to keep  the ticket open so that somebody can look into the issue. Sorry no offend intended.

**Comment by steveaft** [comment]
Is there an example anywhere about how to launch luigi from PyCharm?
Are we supposed to use luigi.cmdline, or luigi.interface or are we supposed to do something like the above? 
When you do this: "Further on luigi.run() does not work out of the box as shown in the example code ... you must add the TaskClass and local_scheduler=True." What is the command you use?

**Comment by debovis** [comment]
@steveaft Any luck getting luigi to run in pycharm?

**Comment by DrOzturk** [comment]
I am using 2017.3.3
I still see this error when I run like

if __name__ == '__main__':
    luigi.run(['PatientCareTask', '--...', '...', ..., '--local-scheduler'])
