### ISSUE TITLE
Memory leaking after executing large amount of tasks

### ISSUE THREAD

**Issue by ZhangXingyaoTHU** [spotify/luigi#2663]
Hi there, we found problem about memory leaking which is similar to #2299 . After executing about 1000 tasks, the memory usage of luigi will rise to about 50GB. Just like that issue, the only going back is a restart.
the current version we used is 2.6.1, will an update work?

@Tarrasch

**Comment by Tarrasch** [comment]
I'm not aware of any memory leaks that have been resolved for luigi. Can it be the tasks themselves that have code that eats memory?

**Comment by ZhangXingyaoTHU** [comment]
> I'm not aware of any memory leaks that have been resolved for luigi. Can it be the tasks themselves that have code that eats memory?

Yes, it could be, especially in what is described in #2299, in the file luigi/luigi/db_task_history.py, the data structure **htask** in function **_get_task** could possess too much resources.

**Comment by Tarrasch** [comment]
Wait wait wait. Is it for the scheduler? Your version is pretty old so it might be worth updating anyway I think. If you really want you can just update the scheduler.

**Comment by tomsing1** [comment]
I also observe this issue, with memory slowly creeping up as jobs as executed. I am using luigi version 2.7.6 with the [luigi.contrib.batch module](https://luigi.readthedocs.io/en/stable/api/luigi.contrib.batch.html) to schedule tasks for workers on AWS Batch. The machine running the scheduler is not executing any tasks itself, e.g. it is only used as the scheduler host.

In case it is helpful, and because recording the task history has been reported in a similar context, here is my `luigi.cfg` file (with `record_task_history` set to False):

```
[core]
log_level=INFO
default-scheduler-host=localhost
default-scheduler-port=8082
max_reschedules=2
parallel_scheduling=False

[worker]
keep_alive=True

[scheduler]
retry_count=2
disable-window-seconds=3600
retry_delay=300
record_task_history=False
state_path=/tmp/state.pickle
```

**Comment by tomsing1** [comment]
I think this issue is still unresolved. Perhaps we can reopen it?

**Comment by Tarrasch** [comment]
The problem is that these issues are very hard to reproduce (as memory increases over time). Python is a Garbage Collected language which I think means that memory leaks only happen in more non-trivial cases. I'm sorry that I can't be of more help this time.

**Comment by ccmaymay** [comment]
I am experiencing a leak in luigi, and I suspect it is the same one.  It is not 50 GB in my case; it is slight, but it is enough to cause problems.  Over time, the system's memory is exhausted and processes start to be killed.

The leak is observable using a simple pipeline structure, using both the local and central schedulers, and when using one worker or several.  Here is a (nearly) minimal working example:

```python
import time
import luigi  # type: ignore


class T(luigi.Task):
    chunk_id = luigi.IntParameter()

    def run(self):
        # Sleep to give us enough time to sample the process's memory usage
        time.sleep(1)
        with self.output().open('w') as f:
            pass

    def output(self):
        return luigi.LocalTarget(f'mwe-data/{self.chunk_id:09}.txt')


class W(luigi.WrapperTask):
    def requires(self):
        return [T(chunk_id) for chunk_id in range(10_000)]
```

In the following section, I share my observations of increasing memory usage for this example pipeline.

Could this issue please be reopened?  Or should I open a new one?

# Experiments

Using psutil, I collected resident memory used (RSS) and [unique memory used (USS)](https://stackoverflow.com/questions/22372960/is-this-explanation-about-vss-rss-pss-uss-accurate) for my (nearly) minimal working example pipeline under a few different settings to illustrate the memory leak.

## Local Scheduler, One Worker

First, I collected RSS and USS for a single worker using the local scheduler.  I'm not an OS/systems expert; I don't know why RSS increases in a stepwise fashion while USS Is more linear.

![mem-usage-rss](https://github.com/spotify/luigi/assets/457238/cac0a02b-edc9-4442-8fbc-c9c5cb6c35d3)

![mem-usage-uss](https://github.com/spotify/luigi/assets/457238/d9501190-2f5f-4e24-9526-aed295292789)

## Local Scheduler, Two Workers

I also collected the same data for each process when using two workers with the local scheduler.  In this case, both USS and RSS appear more linear.  The grey line is the parent process (the scheduler, I suspect).

![mem-usage-rss-2](https://github.com/spotify/luigi/assets/457238/c2e9538f-8009-4020-b253-c8e88a9f2482)

I have clipped the USS plot's y axis, hiding some of the peaks reached by the parent process, to better show the trend in the worker processes.  As for the two rows of worker processes, I believe each worker starts in the bottom row and quickly increases its memory usage until it is in the top row.  Other visualizations (not shown) support this interpretation.

![mem-usage-uss-2](https://github.com/spotify/luigi/assets/457238/7cf6c5cd-6569-4d84-985a-41b0244e55dd)

## Central Scheduler, One Worker

And finally, the same data when using one worker and the central scheduler:

![mem-usage-rss-central](https://github.com/spotify/luigi/assets/457238/f0d00f80-9db0-47d4-bd43-c8182a79cb34)

![mem-usage-uss-central](https://github.com/spotify/luigi/assets/457238/ecf0e363-9a6a-4d8e-8366-0415e8aad8e7)
